--[[
DewDropDown.lua
Defines the table listings for the dropdown lists.
]]

--Invoke all libraries
local AL = LibStub("AceLocale-3.0"):GetLocale("AtlasLoot");
local BabbleBoss = AtlasLoot_GetLocaleLibBabble("LibBabble-Boss-3.0")
local BabbleFaction = AtlasLoot_GetLocaleLibBabble("LibBabble-Faction-3.0")
local BabbleZone = AtlasLoot_GetLocaleLibBabble("LibBabble-Zone-3.0")
local BabbleInventory = AtlasLoot_GetLocaleLibBabble("LibBabble-Inventory-3.0")

--This is a multi-layer table defining the main loot listing.
--Entries have the text to display, loot table or sub table to link to and if the link is to a loot table or sub table
AtlasLoot_DewDropDown = {
	[1] = {				
		[AL["Classic Instances"]] = {				
			[1] = {			
				{ "Raids:", "OldKeys", "Table", "Header" },		
			},			
			[2] = {			
				{ BabbleZone["Molten Core"], "MoltenCore",  "Submenu", "Submenu2" },		
			},			
			[3] = {			
				{ BabbleZone["Zul'Gurub"], "ZulGurub",  "Submenu", "Submenu2" },		
			},			
			[4] = {			
				{ BabbleZone["Onyxia's Lair"], "Onyxia60", "Table", "Submenu2" },	
			},			
			[5] = {			
				{ BabbleZone["Blackwing Lair"], "BlackwingLair",  "Submenu", "Submenu2" },	
			},			
			[6] = {			
				{ BabbleZone["Ruins of Ahn'Qiraj"], "RuinsofAQ",  "Submenu", "Submenu2" },		
			},			
			[7] = {			
				{ BabbleZone["Temple of Ahn'Qiraj"], "TempleofAQ",  "Submenu", "Submenu2" },		
			},			
			[8] = {			
				{ BabbleZone["Naxxramas"], "Naxxramas60",  "Submenu", "Submenu2" },	
			},			
			[9] = {			
				{ "Dungeons:", "OldKeys", "Table", "Header" },		
			},			
			[10] = {			
				{ BabbleZone["Blackfathom Deeps"], "BlackfathomDeeps1", "Table", "none" },		
			},			
			[11] = {			
				{ BabbleZone["Blackrock Depths"], "BlackrockDepths",  "Submenu", "Submenu2" },		
			},			
			[12] = {			
				{ BabbleZone["Lower Blackrock Spire"], "LowerBlackrock", "Submenu", "Submenu2" },		
			},			
			[13] = {			
				{ BabbleZone["Upper Blackrock Spire"], "UpperBlackrock", "Submenu", "Submenu2" },		
			},			
			[14] = {			
				{ BabbleZone["The Deadmines"], "TheDeadmines1", "Table", "none" },		
			},			
			[15] = {			
				[BabbleZone["Dire Maul"]] = {		
					{ BabbleZone["Dire Maul (East)"], "DireMaulEast",  "Submenu", "Submenu2" },
					{ BabbleZone["Dire Maul (West)"], "DireMaulWest",  "Submenu", "Submenu2" },
					{ BabbleZone["Dire Maul (North)"], "DireMaulNorth",  "Submenu", "Submenu2" },
				},		
			},			
			[16] = {			
				{ BabbleZone["Gnomeregan"], "Gnomeregan1", "Table", "none" },
			},			
			[17] = {			
				{ BabbleZone["Maraudon"], "Maraudon1", "Table", "none" },
			},			
			[18] = {			
				{ BabbleZone["Ragefire Chasm"], "RagefireChasm", "Table", "none" },
			},			
			[19] = {			
				{ BabbleZone["Razorfen Downs"], "RazorfenDowns1", "Table", "none" },
			},			
			[20] = {			
				{ BabbleZone["Razorfen Kraul"], "RazorfenKraul1", "Table", "none" },
			},			
			[21] = {			
				{ BabbleZone["Scarlet Monastery"], "Scarlet Monastery",  "Submenu", "none" },
			},			
			[22] = {			
				{ BabbleZone["Scholomance"], "Scholomance",  "Submenu", "Submenu2" },
			},			
			[23] = {			
				{ BabbleZone["Shadowfang Keep"], "ShadowfangKeep1", "Table", "none" },
			},			
			[24] = {			
				{ BabbleZone["The Stockade"], "TheStockade", "Table", "none" },
			},			
			[25] = {			
				{ BabbleZone["Stratholme"], "Stratholme",  "Submenu", "Submenu2" },
			},			
			[26] = {			
				{ BabbleZone["The Temple of Atal'Hakkar"], "SunkenTemple",  "Submenu", "none" },
			},			
			[27] = {			
				{ BabbleZone["Uldaman"], "Uldaman",  "Submenu", "none" },
			},			
			[28] = {			
				{ BabbleZone["Wailing Caverns"], "WailingCaverns1", "Table", "none" },
			},			
			[29] = {			
				{ BabbleZone["Zul'Farrak"], "ZulFarrak",  "Submenu", "none" },
			},
		},
	},			

	[2] = {
		[AL["BC Instances"]] = {
			[1] = {
				{ "Raids:", "BCKeys", "Table", "Header" },
			},
			[2] = {
				{ BabbleZone["Karazhan"], "Karazhan",  "Submenu", "Submenu2" },
			},
			[3] = {
				{ BabbleZone["Gruul's Lair"], "Gruul",  "Submenu", "Submenu2" },
			},
			[4] = {
				{ BabbleZone["Magtheridon's Lair"], "HCMagtheridon", "Table", "Submenu2" },
			},
			[5] = {
				{ BabbleZone["Zul'Aman"], "ZulAman",  "Submenu", "Submenu2" },
			},
			[6] = {
				{ BabbleZone["Serpentshrine Cavern"], "CFRSerpentshrine",  "Submenu", "Submenu2" },
			},
			[7] = {
				{ BabbleZone["The Eye"], "TKEye",  "Submenu", "Submenu2" },
			},
			[8] = {
				{ BabbleZone["Hyjal Summit"], "CoTHyjal",  "Submenu", "Submenu2" },
			},
			[9] = {
				{ BabbleZone["Black Temple"], "BlackTemple",  "Submenu", "Submenu2" },
			},
			[10] = {
				{ BabbleZone["Sunwell Plateau"], "SunwellPlateau",  "Submenu", "Submenu2" },
			},

---- Dungeons -----

			[11] = {
				{ "Dungeons:", "BCKeys", "Table", "Header" },
			},
			
			[12] = {
				{ BabbleZone["The Arcatraz"], "TKArc", "Submenu", "Submenu2" },
			},
			[13] = {
				{ BabbleZone["Auchenai Crypts"], "AuchCrypts", "Submenu", "Submenu2" },
			},
			[14] = {
				{ BabbleZone["The Black Morass"], "CoTBlackMorass", "Submenu", "Submenu2" },
			},
			[15] = {
				{ BabbleZone["The Blood Furnace"], "HCFurnace", "Submenu", "Submenu2" },
			},
			[16] = {
				{ BabbleZone["The Botanica"], "TKBot", "Submenu", "Submenu2" },
			},
			[17] = {
				{ BabbleZone["Hellfire Ramparts"], "HCRamparts", "Submenu", "Submenu2" },
			},
			[18] = {
				{ BabbleZone["Magisters' Terrace"], "MagistersTerrace", "Submenu", "Submenu2" },
			},
			[19] = {
				{ BabbleZone["Mana-Tombs"], "AuchManaTombs", "Submenu", "Submenu2" },
			},
			[20] = {
				{ BabbleZone["The Mechanar"], "TKMech", "Submenu", "Submenu2" },
			},
			[21] = {
				{ BabbleZone["Old Hillsbrad Foothills"], "CoTOldHillsbrad", "Submenu", "Submenu2" },
			},
			[22] = {
				{ BabbleZone["Sethekk Halls"], "AuchSethekk", "Submenu", "Submenu2" },
			},
			[23] = {
				{ BabbleZone["Shadow Labyrinth"], "AuchShadowLab", "Submenu", "Submenu2" },
			},
			[24] = {
				{ BabbleZone["The Shattered Halls"], "HCShatteredHalls", "Submenu", "Submenu2" },
			},
			[25] = {
				{ BabbleZone["The Slave Pens"], "CFRSlavePens", "Submenu", "Submenu2" },
			},
			[26] = {
				{ BabbleZone["The Steamvault"], "CFRSteamvault", "Submenu", "Submenu2" },
			},
			[27] = {
				{ BabbleZone["The Underbog"], "CFRUnderbog", "Submenu", "Submenu2" },
			},

		},
	},
	[3] = {					
		[AL["WotLK Instances"]] = {				
			[1] = {			
				{ "Raids:", "WrathKeys", "Table", "Header" },		
			},			
			[2] = {			
				{ BabbleZone["Naxxramas"], "Naxxramas80", "Submenu", "Submenu2" },		
			},			
			[3] = {			
				{ BabbleZone["The Obsidian Sanctum"], "Sartharion", "Table", "Submenu2" },		
			},			
			[4] = {			
				{ BabbleZone["The Eye of Eternity"], "Malygos", "Table", "Submenu2" },		
			},			
			[5] = {			
				{ BabbleZone["Vault of Archavon"], "VaultofArchavon_A", "Submenu", "Submenu2" },		
			},			
			[6] = {			
				{ BabbleZone["Ulduar"], "Ulduar", "Submenu", "Submenu2" },		
			},			
			[7] = {			
				{ BabbleZone["Trial of the Crusader"], "TrialoftheCrusader_A", "Submenu", "Submenu2" },		
			},			
			[8] = {			
				{ BabbleZone["Onyxia's Lair"], "Onyxia_1", "Table", "Submenu2" },		
			},			
			[9] = {			
				{ BabbleZone["Icecrown Citadel"], "IcecrownCitadel", "Submenu", "Submenu2" },		
			},			
			[10] = {			
				{ BabbleZone["The Ruby Sanctum"], "Halion", "Table", "Submenu2" },		
			},			
			[11] = {			
				{ "Dungeons:", "WrathKeys", "Table", "Header" },		
			},			
           			 [12] = {			
				{ BabbleZone["Ahn'kahet: The Old Kingdom"], "Ahnkahet", "Submenu", "Submenu2" },		
			},			
        	  		[13] = {			
				{ BabbleZone["Azjol-Nerub"], "AzjolNerub", "Submenu", "Submenu2" },		
			},			
			[14] = {			
				{ BabbleZone["Caverns of Time"]..": "..BabbleZone["The Culling of Stratholme"], "CoTStratholme", "Submenu", "Submenu2" },		
			},			
			[15] = {			
				{ BabbleZone["Drak'Tharon Keep"], "DrakTharonKeep", "Submenu", "Submenu2" },		
			},			
			[16] = {			
				{ BabbleZone["The Forge of Souls"], "ForgeofSouls", "Submenu", "Submenu2" },		
			},			
			[17] = {			
				{ BabbleZone["Gundrak"], "Gundrak",  "Submenu", "Submenu2" },		
			},			
			[18] = {			
				{ BabbleZone["Halls of Lightning"], "HallsofLightning",  "Submenu", "Submenu2" },		
			},			
			[19] = {			
				{ BabbleZone["Halls of Reflection"], "HallsofReflection",  "Submenu", "Submenu2" },		
			},			
			[20] = {			
				{ BabbleZone["Halls of Stone"], "HallsofStone",  "Submenu", "Submenu2" },		
			},			
			[21] = {			
				{ BabbleZone["The Nexus"], "TheNexus",  "Submenu", "Submenu2" },		
			},			
			[22] = {			
				{ BabbleZone["The Oculus"], "TheOculus",  "Submenu", "Submenu2" },		
			},			
			[23] = {			
				{ BabbleZone["Pit of Saron"], "PitofSaron",  "Submenu", "Submenu2" },		
			},			
			[24] = {			
				{ BabbleZone["Trial of the Champion"], "TrialoftheChampion",  "Submenu", "Submenu2" },		
			},			
			[25] = {			
				{ BabbleZone["Utgarde Keep"], "UtgardeKeep",  "Submenu", "Submenu2" },		
			},			
			[26] = {			
				{ BabbleZone["Utgarde Pinnacle"], "UtgardePinnacle",  "Submenu", "Submenu2" },		
			},			
			[27] = {			
				{ BabbleZone["The Violet Hold"], "TheVioletHold",  "Submenu", "Submenu2" },		
			},			
		},				
	},					

	[4] = {
		{ AL["Crafting"], "CRAFTINGMENU", "Table", "Submenu2Table" },
	},
	[5] = {
		{ AL["Sets/Collections"], "SETMENU", "Table", "Submenu2Table" },
	},
	[6] = {
		{ AL["PvP Rewards"], "PVPMENU", "Table", "Submenu2Table" },
	},
	[7] = {
		{ AL["World Bosses"], "WorldBosses", "Submenu", "Submenu2Table" },
	},
	[8] = {
		{ AL["Reputation Factions"], "REPMENU", "Table", "Submenu2Table" },
	},
	[9] = {
		{ AL["World Events"], "WORLDEVENTMENU", "Table", "Submenu2Table" },
	},
};
 
AtlasLoot_DewDropDown_SubTables = {
	["BlackrockDepths"] = {
		{ "", "BRDPyron" },
		{ "", "BRDLordRoccor" },
		{ "", "BRDHighInterrogatorGerstahn" },
		{ "", "BRDArena" },
		{ "", "BRDTheldren" },
		{ "", "BRDHoundmaster" },
		{ "", "BRDPyromantLoregrain" },
		{ "", "BRDTheVault" },
		{ "", "BRDWarderStilgiss" },
		{ "", "BRDVerek" },
		{ "", "BRDFineousDarkvire" },
		{ "", "BRDLordIncendius" },
		{ "", "BRDBaelGar" },
		{ "", "BRDGeneralAngerforge" },
		{ "", "BRDGolemLordArgelmach" },
		{ "", "BRDGuzzler" },
		{ "", "CorenDirebrew" },
		{ "", "BRDFlamelash" },
		{ "", "BRDPanzor" },
		{ "", "BRDTomb" },
		{ "", "BRDMagmus" },
		{ "", "BRDImperatorDagranThaurissan" },
		{ "", "BRDPrincess" },
		{ "", "BRDBSPlans" },
		{ "", "BRDTrash" },
		{ "", "VWOWSets1" },
	},
	["LowerBlackrock"] = {
		{ "", "LBRSSpirestoneButcher" },
		{ "", "LBRSOmokk" },
		{ "", "LBRSSpirestoneLord" },
		{ "", "LBRSLordMagus" },
		{ "", "LBRSVosh" },
		{ "", "LBRSVoone" },
		{ "", "LBRSGrayhoof" },
		{ "", "LBRSGrimaxe" },
		{ "", "LBRSSmolderweb" },
		{ "", "LBRSCrystalFang" },
		{ "", "LBRSDoomhowl" },
		{ "", "LBRSZigris" },
		{ "", "LBRSHalycon" },
		{ "", "LBRSSlavener" },
		{ "", "LBRSBashguud" },
		{ "", "LBRSWyrmthalak" },
		{ "", "LBRSFelguard" },
		{ "", "LBRSTrash" },
		{ "", "VWOWSets3" },
	},
	["UpperBlackrock"] = {
		{ "", "UBRSEmberseer" },
		{ "", "UBRSSolakar" },
		{ "", "UBRSFLAME" },
		{ "", "UBRSRunewatcher" },
		{ "", "UBRSAnvilcrack" },
		{ "", "UBRSRend" },
		{ "", "UBRSGyth" },
		{ "", "UBRSBeast" },
		{ "", "UBRSValthalak" },
		{ "", "UBRSDrakkisath" },
		{ "", "UBRSTrash" },
		{ "", "VWOWSets3" },
	},
	["BlackwingLair"] = {
		{ "", "BWLRazorgore" },
		{ "", "BWLVaelastrasz" },
		{ "", "BWLLashlayer" },
		{ "", "BWLFiremaw" },
		{ "", "BWLEbonroc" },
		{ "", "BWLFlamegor" },
		{ "", "BWLChromaggus" },
		{ "", "BWLNefarian1" },
		{ "", "BWLTrashMobs" },
	},
	["Karazhan"] = {
		{ "", "KaraAttumen" },
		{ "", "KaraMoroes" },
		{ "", "KaraMaiden" },
		{ "", "KaraOperaEvent" },
		{ "", "KaraCurator" },
		{ "", "KaraIllhoof" },
		{ "", "KaraAran" },
		{ "", "KaraNetherspite" },
		{ "", "KaraNightbane" },
		{ "", "KaraChess" },
		{ "", "KaraPrince" },
		{ "", "KaraNamed" },
		{ "", "KaraTrash" },
	},
	["MagistersTerrace"] = {
		{ "", "SMTFireheart" },
		{ "", "SMTVexallus" },
		{ "", "SMTDelrissa" },
		{ "", "SMTKaelthas" },
	},
	["MoltenCore"] = {
		{ "", "MCLucifron" },
		{ "", "MCMagmadar" },
		{ "", "MCGehennas" },
		{ "", "MCGarr" },
		{ "", "MCShazzrah" },
		{ "", "MCGeddon" },
		{ "", "MCGolemagg" },
		{ "", "MCSulfuron" },
		{ "", "MCMajordomo" },
		{ "", "MCRagnaros" },
		{ "", "MCTrashMobs" },
		{ "", "MCRANDOMBOSSDROPPS" },
	},
	["Naxxramas60"] = {
		{ "", "NAXPatchwerk" },
		{ "", "NAXGrobbulus" },
		{ "", "NAXGluth" },
		{ "", "NAXThaddius" },
		{ "", "NAXAnubRekhan" },
		{ "", "NAXGrandWidowFearlina" },
		{ "", "NAXMaexxna" },
		{ "", "NAXInstructorRAuvious" },
		{ "", "NAXGothicderHarvester" },
		{ "", "NAXTheFourHorsemen" },
		{ "", "NAXNothderPlaguebringer" },
		{ "", "NAXHeiganderUnclean" },
		{ "", "NAXLoatheb" },
		{ "", "NAXSapphiron" },
		{ "", "NAXKelThuzad" },
		{ "", "NAXTrash" },
	},

	["Scarlet Monastery"] = {
		{ BabbleZone["Armory"], "SMHerod" },
		{ "", "SMCathedral" },
		{ "", "SMGraveyard" },
		{ "", "SMLibrary" },
		{ "", "SMTrash" },
		{ AL["Set: Chain of the Scarlet Crusade"], "VWOWSets1" },
	},
	["Scholomance"] = {
		{ "", "SCHOLOBloodStewardofKirtonos" },
		{ "", "SCHOLOKirtonostheHerald" },
		{ "", "SCHOLOJandiceBarov" },
		{ "", "SCHOLORattlegore" },
		{ "", "SCHOLODeathKnight" },
		{ "", "SCHOLOMarduk" },
		{ "", "SCHOLOVectus" },
		{ "", "SCHOLORasFrostwhisper" },
		{ "", "SCHOLOKormok" },
		{ "", "SCHOLOInstructorMalicia" },
		{ "", "SCHOLODoctorTheolenKrastinov" },
		{ "", "SCHOLOLorekeeperPolkelt" },
		{ "", "SCHOLOTheRavenian" },
		{ "", "SCHOLOLordAlexeiBarov" },
		{ "", "SCHOLOLadyIlluciaBarov" },
		{ "", "SCHOLODarkmasterGandling" },
		{ "", "SCHOLOTrash" },
		{ AL["Set: Necropile Raiment"], "VWOWScholo" },
		{ AL["Set: Cadaverous Garb"], "VWOWScholo" },
		{ AL["Set: Bloodmail Regalia"], "VWOWScholo" },
		{ AL["Set: Deathbone Guardian"], "VWOWScholo" },
	},
	["Stratholme"] = {
		{ BabbleBoss["Skul"], "STRATSkull" },
		{ AtlasLoot_TableNames["STRATStratholmeCourier"][1], "STRATStratholmeCourier" },
		{ BabbleBoss["Fras Siabi"], "STRATFrasSiabi" },
		{ AtlasLoot_TableNames["STRATAtiesh"][1], "STRATAtiesh" },
		{ BabbleBoss["Hearthsinger Forresten"], "STRATHearthsingerForresten" },
		{ BabbleBoss["The Unforgiven"], "STRATTheUnforgiven" },
		{ BabbleBoss["Timmy the Cruel"], "STRATTimmytheCruel" },
		{ AtlasLoot_TableNames["STRATMalorsStrongbox"][1], "STRATMalorsStrongbox" },
		{ BabbleBoss["Crimson Hammersmith"], "STRATCrimsonHammersmith" },
		{ AtlasLoot_TableNames["STRATBSPlansSerenity"][1], "STRATBSPlansSerenity" },
		{ BabbleBoss["Cannon Master Willey"], "STRATCannonMasterWilley" },
		{ BabbleBoss["Archivist Galford"], "STRATArchivistGalford" },
		{ BabbleBoss["Balnazzar"], "STRATBalnazzar" },
		{ AL["Sothos and Jarien"], "STRATSothosJarien" },
		{ AtlasLoot_TableNames["STRATStonespine"][1], "STRATStonespine" },
		{ BabbleBoss["Baroness Anastari"], "STRATBaronessAnastari" },
		{ BabbleBoss["Black Guard Swordsmith"], "STRATBlackGuardSwordsmith" },
		{ AtlasLoot_TableNames["STRATBSPlansCorruption"][1], "STRATBSPlansCorruption" },
		{ BabbleBoss["Nerub'enkan"], "STRATNerubenkan" },
		{ BabbleBoss["Maleki the Pallid"], "STRATMalekithePallid" },
		{ BabbleBoss["Magistrate Barthilas"], "STRATMagistrateBarthilas" },
		{ BabbleBoss["Ramstein the Gorger"], "STRATRamsteintheGorger" },
		{ BabbleBoss["Baron Rivendare"], "STRATBaronRivendare" },
		{ AL["Trash Mobs"], "STRATTrash" },
		{ AL["Set: The Postmaster"], "VWOWSets2" },
	},
	["SunkenTemple"] = {
		{ AtlasLoot_TableNames["STSpawnOfHakkar"][1], "STSpawnOfHakkar" },
		{ AtlasLoot_TableNames["STTrollMinibosses"][1], "STTrollMinibosses" },
		{ BabbleBoss["Atal'alarion"], "STAtalalarion" },
		{ BabbleBoss["Dreamscythe"], "STDreamscythe" },
		{ BabbleBoss["Weaver"], "STWeaver"},
		{ BabbleBoss["Avatar of Hakkar"], "STAvatarofHakkar" },
		{ BabbleBoss["Jammal'an the Prophet"], "STJammalan" },
		{ BabbleBoss["Ogom the Wretched"], "STOgom" },
		{ BabbleBoss["Morphaz"], "STMorphaz" },
		{ BabbleBoss["Hazzas"], "STHazzas" },
		{ BabbleBoss["Shade of Eranikus"], "STEranikus" },
		{ AL["Trash Mobs"], "STTrash" },
	},
	["Uldaman"] = {
		{ BabbleBoss["Digmaster Shovelphlange"], "UldShovelphlange" },
		{ AtlasLoot_TableNames["UldBaelog"][1], "UldBaelog" },
		{ BabbleBoss["Revelosh"], "UldRevelosh" },
		{ BabbleBoss["Ironaya"], "UldIronaya" },
		{ BabbleBoss["Ancient Stone Keeper"], "UldAncientStoneKeeper" },
		{ BabbleBoss["Galgann Firehammer"], "UldGalgannFirehammer" },
		{ BabbleBoss["Grimlok"], "UldGrimlok" },
		{ BabbleBoss["Archaedas"], "UldArchaedas" },
		{ AL["Trash Mobs"], "UldTrash" },
	},
	["ZulGurub"] = {
		{ BabbleBoss["High Priestess Jeklik"], "ZGJeklik" },
		{ BabbleBoss["High Priest Venoxis"], "ZGVenoxis" },
		{ BabbleBoss["High Priestess Mar'li"], "ZGMarli" },
		{ BabbleBoss["Bloodlord Mandokir"], "ZGMandokir" },
		{ BabbleZone["Zul'Gurub"], "ZGEdgeofMadness" },
		{ BabbleBoss["Gahz'ranka"], "ZGGahzranka" },
		{ BabbleBoss["High Priest Thekal"], "ZGThekal" },
		{ BabbleBoss["High Priestess Arlokk"], "ZGArlokk" },
		{ BabbleBoss["Jin'do the Hexxer"], "ZGJindo" },
		{ BabbleBoss["Hakkar"], "ZGHakkar" },
		{ AL["Random Boss Loot"], "ZGShared" },
		{ AL["Trash Mobs"], "ZGTrash1" },
		{ AL["ZG Enchants"], "ZGEnchants" },
	},
	["CoTOldHillsbrad"] = {
		{ "", "CoTHillsbradDrake" },
		{ "", "CoTHillsbradSkarloc" },
		{ "", "CoTHillsbradHunter" },
		{ "", "CoTHillsbradHunterHeroic" },
		{ AL["Trash Mobs"], "CoTTrash" },
	},
	["CoTBlackMorass"] = {
		{ "", "CoTMorassDeja" },
		{ "", "CoTMorassTemporus" },
		{ "", "CoTMorassAeonus" },
		{ AL["Trash Mobs"], "CoTTrash" },
	},
	["CoTHyjal"] = {
		{ "", "MountHyjalWinterchill" },
		{ "", "MountHyjalAnetheron" },
		{ "", "MountHyjalKazrogal" },
		{ "", "MountHyjalAzgalor" },
		{ "", "MountHyjalArchimonde" },
		{ AL["Trash Mobs"], "MountHyjalTrash" },
	},
	["DireMaulEast"] = {
		{ BabbleBoss["Pusillin"], "DMEPusillin" },
		{ BabbleBoss["Zevrim Thornhoof"], "DMEZevrimThornhoof" },
		{ BabbleBoss["Hydrospawn"], "DMEHydro" },
		{ BabbleBoss["Lethtendris"], "DMELethtendris" },
		{ BabbleBoss["Pimgib"], "DMEPimgib" },
		{ BabbleBoss["Alzzin the Wildshaper"], "DMEAlzzin" },
		{ BabbleBoss["Isalien"], "DMEIsalien" },
		{ AL["Trash Mobs"], "DMETrash" },
		{ AL["Dire Maul Books"], "DMBooks" },
	},
	["DireMaulWest"] = {
		{ BabbleBoss["Tendris Warpwood"], "DMWTendrisWarpwood" },
		{ BabbleBoss["Illyanna Ravenoak"], "DMWIllyannaRavenoak" },
		{ BabbleBoss["Magister Kalendris"], "DMWMagisterKalendris" },
		{ BabbleBoss["Tsu'zee"], "DMWTsuzee" },
		{ BabbleBoss["Immol'thar"], "DMWImmolthar" },
		{ BabbleBoss["Lord Hel'nurath"], "DMWHelnurath" },
		{ BabbleBoss["Prince Tortheldrin"], "DMWPrinceTortheldrin" },
		{ AL["Trash Mobs"], "DMWTrash" },
		{ AL["Dire Maul Books"], "DMBooks" },
	},
	["DireMaulNorth"] = {
		{ BabbleBoss["Guard Mol'dar"], "DMNGuardMoldar" },
		{ BabbleBoss["Stomper Kreeg"], "DMNStomperKreeg" },
		{ BabbleBoss["Guard Fengus"], "DMNGuardFengus" },
		{ AtlasLoot_TableNames["DMNThimblejack"][1], "DMNThimblejack" },
		{ BabbleBoss["Guard Slip'kik"], "DMNGuardSlipkik" },
		{ BabbleBoss["Captain Kromcrush"], "DMNCaptainKromcrush" },
		{ BabbleBoss["King Gordok"], "DMNKingGordok" },
		{ BabbleBoss["Cho'Rush the Observer"], "DMNChoRush" },
		{ AL["Tribute Run"], "DMNTRIBUTERUN" },
		{ AL["Dire Maul Books"], "DMBooks" },
	},
	["RuinsofAQ"] = {
		{ BabbleBoss["Kurinnaxx"], "AQ20Kurinnaxx" },
		{ BabbleBoss["General Rajaxx"], "AQ20Rajaxx" },
		{ BabbleBoss["Moam"], "AQ20Moam" },
		{ BabbleBoss["Buru the Gorger"], "AQ20Buru" },
		{ BabbleBoss["Ayamiss the Hunter"], "AQ20Ayamiss" },
		{ BabbleBoss["Ossirian the Unscarred"], "AQ20Ossirian" },
		{ AL["Trash Mobs"], "AQ20Trash" },
		{ AL["Class Books"], "AQ20ClassBooks" },
		{ AL["AQ Enchants"], "AQEnchants" },
		{ AL["Ruins of Ahn'Qiraj Sets"], "AQ20Sets1" },
	},
	["TempleofAQ"] = {
		{ BabbleBoss["The Prophet Skeram"], "AQ40Skeram" },
		{ BabbleBoss["The Bug Family"], "AQ40Vem" },
		{ BabbleBoss["Battleguard Sartura"], "AQ40Sartura" },
		{ BabbleBoss["Fankriss the Unyielding"], "AQ40Fankriss" },
		{ BabbleBoss["Viscidus"], "AQ40Viscidus" },
		{ BabbleBoss["Princess Huhuran"], "AQ40Huhuran" },
		{ BabbleBoss["The Twin Emperors"], "AQ40Emperors" },
		{ BabbleBoss["Ouro"], "AQ40Ouro" },
		{ BabbleBoss["C'Thun"], "AQ40CThun" },
		{ AL["Trash Mobs"], "AQ40Trash1" },
		{ AL["AQ Enchants"], "AQEnchants" },
		{ AL["AQ Opening Quest Chain"], "AQOpening" },
	},
	["ZulFarrak"] = {
		{ BabbleBoss["Antu'sul"], "ZFAntusul" },
		{ BabbleBoss["Theka the Martyr"], "ZFThekatheMartyr" },
		{ BabbleBoss["Witch Doctor Zum'rah"], "ZFWitchDoctorZumrah" },
		{ BabbleBoss["Nekrum Gutchewer"], "ZFNekrumGutchewer" },
		{ BabbleBoss["Shadowpriest Sezz'ziz"], "ZFSezzziz" },
		{ BabbleBoss["Dustwraith"], "ZFDustwraith" },
		{ BabbleBoss["Sergeant Bly"], "ZFSergeantBly" },
		{ BabbleBoss["Sandfury Executioner"], "ZFSandfury" },
		{ BabbleBoss["Hydromancer Velratha"], "ZFHydromancerVelratha" },
		{ BabbleBoss["Gahz'rilla"], "ZFGahzrilla" },
		{ BabbleBoss["Chief Ukorz Sandscalp"], "ZFChiefUkorzSandscalp" },
		{ BabbleBoss["Zerillis"], "ZFZerillis" },
		{ AL["Trash Mobs"], "ZFTrash" },
	},
	["AuchManaTombs"] = {
		{ "", "AuchManaPandemonius" },
		{ "", "AuchManaTavarok" },
		{ "", "AuchManaNexusPrince" },
		{ "", "AuchManaNexusPrinceHeroic" },
		{ "", "AuchManaYorHeroic" },
		{ AL["Trash Mobs"], "AuchTrash" },
	},
	["AuchCrypts"] = {
		{ "", "AuchCryptsShirrak" },
		{ "", "AuchCryptsExarch" },
		{ "", "AuchCryptsAvatar" },
		{ AL["Trash Mobs"], "AuchTrash" },
	},
	["AuchSethekk"] = {
		{ "", "AuchSethekkDarkweaver" },
		{ "", "AuchSethekkTalonKing" },
		{ "", "AuchSethekkRavenGod" },
		{ AL["Trash Mobs"], "AuchTrash" },
	},
	["AuchShadowLab"] = {
		{ "", "AuchShadowHellmaw" },
		{ "", "AuchShadowBlackheart" },
		{ "", "AuchShadowGrandmaster" },
		{ "", "AuchShadowMurmur" },
		{ AL["Trash Mobs"], "AuchTrash" },
	},
	["BlackTemple"] = {
		{ "", "BTNajentus" },
		{ "", "BTSupremus" },
		{ "", "BTAkama" },
		{ "", "BTGorefiend" },
		{ "", "BTBloodboil" },
		{ "", "BTEssencofSouls" },
		{ "", "BTShahraz" },
		{ "", "BTCouncil" },
		{ "", "BTIllidanStormrage" },
		{ AL["BT Patterns/Plans"], "BTPatterns" },
		{ AL["Trash Mobs"], "BTTrash" },
	},
	["CFRSlavePens"] = {
		{ "", "CFRSlaveMennu" },
		{ "", "CFRSlaveRokmar" },
		{ "", "CFRSlaveQuagmirran" },
		{ "", "LordAhune" },
	},
	["CFRUnderbog"] = {
		{ "", "CFRUnderHungarfen" },
		{ "", "CFRUnderGhazan" },
		{ "", "CFRUnderSwamplord" },
		{ "", "CFRUnderStalker" },
		{ "", "CFRUnderStalkerHeroic" },
	},
	["CFRSteamvault"] = {
		{ "", "CFRSteamThespia" },
		{ "", "CFRSteamSteamrigger" },
		{ "", "CFRSteamWarlord" },
		{ AL["Trash Mobs"], "CFRSteamTrash" },
	},
	["CFRSerpentshrine"] = {
		{ "", "CFRSerpentHydross" },
		{ "", "CFRSerpentLurker" },
		{ "", "CFRSerpentLeotheras" },
		{ "", "CFRSerpentKarathress" },
		{ "", "CFRSerpentMorogrim" },
		{ "", "CFRSerpentVashj" },
		{ AL["Trash Mobs"], "CFRSerpentTrash" },
	},
	["Gruul"] = {
		{ "", "GruulsLairHighKingMaulgar" },
		{ "", "GruulGruul" },
	},
	["HCRamparts"] = {
		{ "", "HCRampWatchkeeper" },
		{ "", "HCRampOmor" },
		{ "", "HCRampVazruden" },
		{ "", "HCRampVazrudenHeroic" },
	},
	["HCFurnace"] = {
		{ "", "HCFurnaceMaker" },
		{ "", "HCFurnaceBroggok" },
		{ "", "HCFurnaceBreaker" },
	},
	["HCShatteredHalls"] = {
		{ "", "HCHallsNethekurse" },
		{ "", "HCHallsPorung" },
		{ "", "HCHallsOmrogg" },
		{ "", "HCHallsKargath" },
		{ AL["Trash Mobs"], "HCHallsTrash" },
	},
	["TKMech"] = {
		{ "", "TKMechCacheoftheLegion" },
		{ "", "TKMechCapacitus" },
		{ "", "TKMechSepethrea" },
		{ "", "TKMechCalc" },
		{ "", "TKMechCalcHeroic" },
		{ AL["Trash Mobs"], "TKTrash" },
	},
	["TKBot"] = {
		{ "", "TKBotSarannis" },
		{ "", "TKBotFreywinn" },
		{ "", "TKBotThorngrin" },
		{ "", "TKBotLaj" },
		{ "", "TKBotSplinter" },
		{ "", "TKBotSplinterHeroic" },
		{ AL["Trash Mobs"], "TKTrash" },
	},
	["TKArc"] = {
		{ "", "TKArcUnbound" },
		{ "", "TKArcScryer" },
		{ "", "TKArcDalliah" },
		{ "", "TKArcHarbinger" },
		{ AL["Trash Mobs"], "TKTrash" },
	},
	["TKEye"] = {
		{ "", "TKEyeAlar" },
		{ "", "TKEyeVoidReaver" },
		{ "", "TKEyeSolarian" },
		{ "", "TKEyeKaelthas" },
		{ "", "TKEyeLegendaries" },
		{ AL["Trash Mobs"], "TKEyeTrash" },
	},
	["ZulAman"] = {
		{ "", "ZANalorakk" },
		{ "", "ZAAkilZon" },
		{ "", "ZAJanAlai" },
		{ "", "ZAHalazzi" },
		{ "", "ZAMalacrass" },
		{ "", "ZAZuljin" },
		{ AL["Timed Reward Chest"], "ZATimedChest" },
		{ AL["Trash Mobs"], "ZATrash" },
	},
	["SunwellPlateau"] = {
		{ "", "SPKalecgos" },
		{ "", "SPBrutallus" },
		{ "", "SPFelmyst" },
		{ "", "SPEredarTwins" },
		{ "", "SPMuru" },
		{ "", "SPKiljaeden" },
		{ "", "SPPatterns" },
		{ AL["Trash Mobs"], "SPTrash" },
	},
	["Ahnkahet"] = {
		{ "", "AhnkahetNadox" },
		{ "", "AhnkahetTaldaram" },
		{ "", "AhnkahetAmanitarHEROIC" },
		{ "", "AhnkahetJedoga" },
		{ "", "AhnkahetVolazj" },
		{ "", "AhnkahetTrash" },
	},
	["AzjolNerub"] = {
		{ "", "AzjolNerubKrikthir" },
		{ "", "AzjolNerubHadronox" },
		{ "", "AzjolNerubAnubarak" },
		{ "", "AzjolNerubTrash" },
	},
	["CoTStratholme"] = {
		{ "", "CoTStratholmeMeathook" },
		{ "", "CoTStratholmeEpoch" },
		{ "", "CoTStratholmeSalramm" },
		{ "", "CoTStratholmeInfiniteCorruptorHEROIC" },
		{ "", "CoTStratholmeMalGanis" },
		{ "", "CoTStratholmeTrash" },
	},
	["DrakTharonKeep"] = {
		{ "", "DrakTharonKeepTrollgore" },
		{ "", "DrakTharonKeepNovos" },
		{ "", "DrakTharonKeepKingDred" },
		{ "", "DrakTharonKeepTharonja" },
		{ "", "DrakTharonKeepTrash" },
	},
	["Gundrak"] = {
		{ "", "GundrakSladran" },
		{ "", "GundrakColossus" },
		{ "", "GundrakMoorabi" },
		{ "", "GundrakEckHEROIC" },
		{ "", "GundrakGaldarah" },
		{ "", "GundrakTrash" },
	},
	["HallsofLightning"] = {
		{ "", "HallsofLightningBjarngrim" },
		{ "", "HallsofLightningVolkhan" },
		{ "", "HallsofLightningIonar" },
		{ "", "HallsofLightningLoken" },
		{ "", "HallsofLightningTrash" },
	},
	["HallsofStone"] = {
		{ "", "HallsofStoneMaiden" },
		{ "", "HallsofStoneKrystallus" },
		{ "", "HallsofStoneTribunal" },
		{ "", "HallsofStoneSjonnir" },
		{ "", "HallsofStoneTrash" },
	},
	["Ulduar"] = {
		{ "", "UlduarLeviathan" },
		{ "", "UlduarIgnis" },
		{ "", "UlduarRazorscale" },
		{ "", "UlduarDeconstructor" },
		{ "", "UlduarIronCouncil" },
		{ "", "UlduarKologarn" },
		{ "", "UlduarAlgalon" },
		{ "", "UlduarAuriaya" },
		{ "", "UlduarHodir" },
		{ "", "UlduarThorim" },
		{ "", "UlduarFreya" },
		{ "", "UlduarMimiron" },
		{ "", "UlduarVezax" },
		{ "", "UlduarYoggSaron" },
		{ "", "UlduarTrash" },
		{ "", "UlduarPatterns" },
	},
	["UtgardeKeep"] = {
		{ "", "UtgardeKeepKeleseth" },
		{ "", "UtgardeKeepSkarvald" },
		{ "", "UtgardeKeepIngvar" },
		{ "", "UtgardeKeepTrash" },
	},
	["UtgardePinnacle"] = {
		{ "", "UPSkadi" },
		{ "", "UPYmiron" },
		{ "", "UPSorrowgrave" },
		{ "", "UPPalehoof" },
		{ "", "UPTrash" },
	},
	["TheVioletHold"] = {
		{ "", "VioletHoldErekem" },
		{ "", "VioletHoldZuramat" },
		{ "", "VioletHoldXevozz" },
		{ "", "VioletHoldIchoron" },
		{ "", "VioletHoldMoragg" },
		{ "", "VioletHoldLavanthor" },
		{ "", "VioletHoldCyanigosa" },
		{ "", "VioletHoldTrash" },
	},
	["TheOculus"] = {
		{ "", "OcuDrakos" },
		{ "", "OcuUrom" },
		{ "", "OcuCloudstrider" },
		{ "", "OcuEregos" },
		{ "", "OcuTrash" },
	},
	["TrialoftheChampion"] = {
		{ "", "TrialoftheChampionChampions" },
		{ "", "TrialoftheChampionConfessorPaletress" },
		{ "", "TrialoftheChampionEadricthePure" },
		{ "", "TrialoftheChampionBlackKnight" },
	},
	["TrialoftheCrusader_A"] = {
		{ BabbleBoss["The Beasts of Northrend"], "TrialoftheCrusaderNorthrendBeasts_A" },
		{ BabbleBoss["Lord Jaraxxus"], "TrialoftheCrusaderLordJaraxxus_A" },
		{ AL["Faction Champions"], "TrialoftheCrusaderFactionChampions_A" },
		{ BabbleBoss["The Twin Val'kyr"], "TrialoftheCrusaderTwinValkyrs_A" },
		{ BabbleBoss["Anub'arak"], "TrialoftheCrusaderAnubarak_A" },
		{ AL["Tribute Run"], "TrialoftheCrusaderTributeHEROIC_A" },
		{ AL["Trial of the Crusader Patterns/Plans"], "TrialoftheCrusaderPatterns_A" },
	},
	["VaultofArchavon_A"] = {
		{ BabbleBoss["Archavon the Stone Watcher"], "VaultofArchavonArchavon1" },
		{ BabbleBoss["Emalon the Storm Watcher"], "VaultofArchavonEmalon1" },
		{ BabbleBoss["Koralon the Flame Watcher"], "VaultofArchavonKoralon1_A" },
		{ BabbleBoss["Toravon the Ice Watcher"], "VaultofArchavonToravon1" },
	},
	["Naxxramas80"] = {
		{ AtlasLoot_TableNames["Naxx80Patchwerk"][1].." ("..AL["Construct Quarter"]..")", "Naxx80Patchwerk" },
		{ AtlasLoot_TableNames["Naxx80Grobbulus"][1].." ("..AL["Construct Quarter"]..")", "Naxx80Grobbulus" },
		{ AtlasLoot_TableNames["Naxx80Gluth1"][1].." ("..AL["Construct Quarter"]..")", "Naxx80Gluth1" },
		{ AtlasLoot_TableNames["Naxx80Thaddius"][1].." ("..AL["Construct Quarter"]..")", "Naxx80Thaddius" },
		{ AtlasLoot_TableNames["Naxx80AnubRekhan"][1].." ("..AL["Arachnid Quarter"]..")", "Naxx80AnubRekhan" },
		{ AtlasLoot_TableNames["Naxx80Faerlina"][1].." ("..AL["Arachnid Quarter"]..")", "Naxx80Faerlina" },
		{ AtlasLoot_TableNames["Naxx80Maexxna"][1].." ("..AL["Arachnid Quarter"]..")", "Naxx80Maexxna" },
		{ AtlasLoot_TableNames["Naxx80Razuvious"][1].." ("..AL["Military Quarter"]..")", "Naxx80Razuvious" },
		{ AtlasLoot_TableNames["Naxx80Gothik"][1].." ("..AL["Military Quarter"]..")", "Naxx80Gothik" },
		{ AtlasLoot_TableNames["Naxx80FourHorsemen"][1].." ("..AL["Military Quarter"]..")", "Naxx80FourHorsemen" },
		{ AtlasLoot_TableNames["Naxx80Noth"][1].." ("..AL["Plague Quarter"]..")", "Naxx80Noth" },
		{ AtlasLoot_TableNames["Naxx80Heigan"][1].." ("..AL["Plague Quarter"]..")", "Naxx80Heigan" },
		{ AtlasLoot_TableNames["Naxx80Loatheb"][1].." ("..AL["Plague Quarter"]..")", "Naxx80Loatheb" },
		{ AtlasLoot_TableNames["Naxx80Sapphiron"][1].." ("..AL["Frostwyrm Lair"]..")", "Naxx80Sapphiron" },
		{ AtlasLoot_TableNames["Naxx80KelThuzad"][1].." ("..AL["Frostwyrm Lair"]..")", "Naxx80KelThuzad" },
		{ "", "Naxx80Trash" },
	},
	["TheNexus"] = {
		{ "", "TheNexusTelestra" },
		{ "", "TheNexusAnomalus"},
		{ "", "TheNexusOrmorok" },
		{ "", "TheNexusKolurgStoutbeardHEROIC"},
		{ "", "TheNexusKeristrasza" },
	},
	["WorldBosses"] = {
		{ "", "WorldBossesClassic" },
		{ "", "DEmeriss" },
		{ "", "DLethon"},
		{ "", "DTaerar" },
		{ "", "DYsondre" },
		{ "", "Kazzak60" },
		{ "", "Setis" },
		{ "", "WorldBossesBC"},
	},
	["ForgeofSouls"] = {
		{ "", "FoSBronjahm" },
		{ "", "FoSDevourer" },
		{ "", "FHTrashMobs" },
	},
	["PitofSaron"] = {
		{ "", "PoSGarfrost" },
		{ "", "PoSKrickIck" },
		{ "", "PoSTyrannus" },
		{ "", "FHTrashMobs" },
	},
	["HallsofReflection"] = {
		{ "", "HoRFalric" },
		{ "", "HoRMarwyn" },
		{ "", "HoRLichKing" },
		{ "", "FHTrashMobs" },
	},
	["IcecrownCitadel"] = {
		{ "", "ICCLordMarrowgar" },
		{ "", "ICCLadyDeathwhisper" },
		{ "", "ICCGunshipBattle" },
		{ "", "ICCSaurfang" },
		{ "", "ICCFestergut" },
		{ "", "ICCRotface" },
		{ "", "ICCPutricide" },
		{ "", "ICCCouncil" },
		{ "", "ICCLanathel" },
		{ "", "ICCValithria" },
		{ "", "ICCSindragosa" },
		{ "", "ICCLichKing" },
		{ "", "ICCTrash25Man" },
	},
};

AtlasLoot_DewDropDown_SubTables2 = {
	
	--Classic Instances
	
	["BlackrockDepths"] = {
		{ "", 1, "Normal", "" }, 
		{ "", 2, "Heroic", 3 },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	["LowerBlackrock"] = {
		{ "", 1, "Normal", "" },
		{ "", 2, "Heroic", 3 },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	["UpperBlackrock"] = {
		{ "", 1, "Normal", "" },
		{ "", 2, "Heroic", 3 },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	
	["Scarlet Monastery"] = { { "", 1, "Normal", "" }, { "", 2, "Bloodforged", 1 }, },
	["BlackfathomDeeps1"] = { { "", 1, "Normal", "" }, { "", 2, "Bloodforged", 1 }, },
	["BlackfathomDeeps2"] = { { "", 1, "Normal", "" }, { "", 2, "Bloodforged", 1 }, },
	
	
	
	["Scholomance"] = {
		{ "", 1, "Normal", "" },
		{ "", 2, "Heroic", 3 },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	["Stratholme"] = {
		{ "", 1, "Normal", "" },
		{ "", 2, "Heroic", 3 },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	["SunkenTemple"] = { { "", 1, "Normal", "" }, { "", 2, "Bloodforged", 1 }, },
	["Uldaman"] = { { "", 1, "Normal", "" }, { "", 2, "Bloodforged", 1 }, },
	
	["DireMaulEast"] = {
		{ "", 1, "Normal", "" },
		{ "", 2, "Heroic", 3 },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	["DireMaulWest"] = {
		{ "", 1, "Normal", "" },
		{ "", 2, "Heroic", 3 },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	["DireMaulNorth"] = {
		{ "", 1, "Normal", "" },
		{ "", 2, "Heroic", 3 },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	["ZulFarrak"] = { { "", 1, "Normal", "" }, { "", 2, "Bloodforged", 1 }, },
	
	--Classic Raids
	
	["MoltenCore"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
	["Onyxia60"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
	["ZulGurub"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
	["BlackwingLair"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
	["RuinsofAQ"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
	["TempleofAQ"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
	["Naxxramas60"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
	
	--BC Instances
	
	["MagistersTerrace"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	["CoTOldHillsbrad"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	["CoTBlackMorass"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},	
	["AuchManaTombs"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	["AuchCrypts"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	["AuchSethekk"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	["AuchShadowLab"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	["CFRSlavePens"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	["CFRUnderbog"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	["CFRSteamvault"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	["HCRamparts"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	["HCFurnace"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	["HCShatteredHalls"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	["TKMech"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	["TKBot"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	["TKArc"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 3, "Mythic", 4 },
		{ "", 4, "Mythic1", 5 },
		{ "", 5, "Mythic2", 6 },
		{ "", 6, "Mythic3", 7 },
		{ "", 7, "Mythic4", 8 },
		{ "", 8, "Mythic5", 9 },
		{ "", 9, "Mythic6", 10 },
		{ "", 10, "Mythic7", 11 },
		{ "", 11, "Mythic8", 12 },
		{ "", 12, "Mythic9", 13 },
		{ "", 13, "Mythic10", 14 },	
		{ "", 14, "Bloodforged", 1 },
	},
	
	--BC Raids
	
	["Karazhan"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
	["BlackTemple"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
	["CoTHyjal"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
	["CFRSerpentshrine"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
	["Gruul"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
	["HCMagtheridon"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
	["TKEye"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
	["ZulAman"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
	["SunwellPlateau"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
		
	--Wrath Instances
	
	["Ahnkahet"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 2, "Mythic", 4 },
		{ "", 3, "Bloodforged", 1 },
	},
	["AzjolNerub"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 2, "Mythic", 4 },
		{ "", 3, "Bloodforged", 1 },
	},
	["CoTStratholme"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 2, "Mythic", 4 },
		{ "", 3, "Bloodforged", 1 },
	},
	["DrakTharonKeep"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 2, "Mythic", 4 },
		{ "", 3, "Bloodforged", 1 },
	},
	["Gundrak"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 2, "Mythic", 4 },
		{ "", 3, "Bloodforged", 1 },
	},
	["HallsofLightning"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 2, "Mythic", 4 },
		{ "", 3, "Bloodforged", 1 },
	},
	["HallsofStone"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 2, "Mythic", 4 },
		{ "", 3, "Bloodforged", 1 },
	},
	["UtgardeKeep"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 2, "Mythic", 4 },
		{ "", 3, "Bloodforged", 1 },
	},
	["UtgardePinnacle"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 2, "Mythic", 4 },
		{ "", 3, "Bloodforged", 1 },
	},
	["TheVioletHold"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 2, "Mythic", 4 },
		{ "", 3, "Bloodforged", 1 },
	},
	["TheOculus"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 2, "Mythic", 4 },
		{ "", 3, "Bloodforged", 1 },
	},
	["TrialoftheChampion"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 2, "Mythic", 4 },
		{ "", 3, "Bloodforged", 1 },
	},
	["TheNexus"] = {
		{ "", 1, "NormalHEROIC", "" },
		{ "", 2, "Mythic", 4 },
		{ "", 3, "Bloodforged", 1 },
	},
	
	--Wrath Raids
	
	["Ulduar"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},

	["TrialoftheCrusader_A"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
	["VaultofArchavon_A"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
	["Naxxramas80"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
	["ForgeofSouls"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
	["PitofSaron"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
	["HallsofReflection"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
	["IcecrownCitadel"] = {
		{ "", 1, "NormalFLEX", "" },
		{ "", 2, "HeroicFLEX", 3 },
		{ "", 3, "Ascended", 4 },
		{ "", 4, "Bloodforged", 1 },
	},
		
	-- Tier Sets
	
	["ZGSets1"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["ZGSets2"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["ZGSets3"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	
	["AQ20Sets1"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["AQ20Sets2"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	
	["AQ40Sets1"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["AQ40Sets2"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["AQ40Sets3"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	
	--Tier 1/2/3
	
	["T1T2Druid"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T3Druid"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T1T2Mage"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T3Mage"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T1T2Priest"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T3Priest"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T1T2Shaman"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T3Shaman"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T1T2Warrior"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T3Warrior"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T1T2Hunter"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T3Hunter"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T1T2Paladin"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T3Paladin"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T1T2Rogue"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T3Rogue"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T1T2Warlock"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T3Warlock"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T1T2DPSWarrior"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T3DPSWarrior"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	
	--Tier 4
	
	["T4DruidBalance"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T4DruidFeral"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T4DruidRestoration"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T4Hunter"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T4Mage"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T4PaladinHoly"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T4PaladinProtection"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T4PaladinRetribution"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T4PriestHoly"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T4PriestShadow"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T4Rogue"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T4ShamanElemental"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T4ShamanEnhancement"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T4ShamanRestoration"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T4Warlock"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T4WarriorFury"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T4WarriorProtection"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	
	-- Tier 5
	
	["T5DruidBalance"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T5DruidFeral"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T5DruidRestoration"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T5Hunter"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T5Mage"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T5PaladinHoly"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T5PaladinProtection"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T5PaladinRetribution"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T5PriestHoly"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T5PriestShadow"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T5Rogue"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T5ShamanElemental"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T5ShamanEnhancement"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T5ShamanRestoration"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T5Warlock"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T5WarriorFury"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T5WarriorProtection"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	
	-- Tier 6
	
	["T6DruidBalance"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T6DruidFeral"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T6DruidRestoration"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T6Hunter"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T6Mage"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T6PaladinHoly"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T6PaladinProtection"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T6PaladinRetribution"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T6PriestHoly"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T6PriestShadow"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T6Rogue"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T6ShamanElemental"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T6ShamanEnhancement"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T6ShamanRestoration"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T6Warlock"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T6WarriorFury"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T6WarriorProtection"] = { { "", 1, "NormalFLEX", "" }, { "", 2, "HeroicFLEX", 3 }, { "", 3, "Ascended", 4 }, { "", 4, "Bloodforged", 1 }, },
	
	-- Dungeon Set 1/2
	
	["T0Druid"] = { { "", 1, "Normal", "" }, { "", 2, "Heroic", 3 }, { "", 3, "Mythic", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T0Mage"] = { { "", 1, "Normal", "" }, { "", 2, "Heroic", 3 }, { "", 3, "Mythic", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T0Priest"] = { { "", 1, "Normal", "" }, { "", 2, "Heroic", 3 }, { "", 3, "Mythic", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T0Shaman"] = { { "", 1, "Normal", "" }, { "", 2, "Heroic", 3 }, { "", 3, "Mythic", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T0Warrior"] = { { "", 1, "Normal", "" }, { "", 2, "Heroic", 3 }, { "", 3, "Mythic", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T0Hunter"] = { { "", 1, "Normal", "" }, { "", 2, "Heroic", 3 }, { "", 3, "Mythic", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T0Paladin"] = { { "", 1, "Normal", "" }, { "", 2, "Heroic", 3 }, { "", 3, "Mythic", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T0Rogue"] = { { "", 1, "Normal", "" }, { "", 2, "Heroic", 3 }, { "", 3, "Mythic", 4 }, { "", 4, "Bloodforged", 1 }, },
	["T0Warlock"] = { { "", 1, "Normal", "" }, { "", 2, "Heroic", 3 }, { "", 3, "Mythic", 4 }, { "", 4, "Bloodforged", 1 }, },
	
	-- Dungeon Set 3
	
	["DS3Cloth"] = { { "", 1, "Normal", "" }, { "", 2, "Heroic", 3 }, { "", 3, "Mythic", 4 }, { "", 4, "Bloodforged", 1 }, },
	["DS3Leather"] = { { "", 1, "Normal", "" }, { "", 2, "Heroic", 3 }, { "", 3, "Mythic", 4 }, { "", 4, "Bloodforged", 1 }, },
	["DS3Mail"] = { { "", 1, "Normal", "" }, { "", 2, "Heroic", 3 }, { "", 3, "Mythic", 4 }, { "", 4, "Bloodforged", 1 }, },
	["DS3Plate"] = { { "", 1, "Normal", "" }, { "", 2, "Heroic", 3 }, { "", 3, "Mythic", 4 }, { "", 4, "Bloodforged", 1 }, },
	
	-- BlackSmithing
	
	["SmithingArmorOld1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["SmithingArmorOld2"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["SmithingArmorOld3"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["SmithingArmorOld4"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["SmithingArmorOld5"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["SmithingArmorBC1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["SmithingArmorBC2"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["SmithingArmorBC3"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["SmithingArmorWrath1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["SmithingArmorWrath2"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["SmithingArmorWrath3"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["SmithingArmorWrath4"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["SmithingWeaponOld1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["SmithingWeaponOld2"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["SmithingWeaponOld3"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["SmithingWeaponBC1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["SmithingWeaponBC2"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["SmithingWeaponWrath1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["Armorsmith1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["Weaponsmith1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["Axesmith1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["Hammersmith1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["Swordsmith1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	
	-- Engineering
	
	["EngineeringArmor1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["EngineeringArmor2"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["EngineeringArmor3"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["EngineeringArmor4"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["EngineeringWeapon1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	
	-- Leatherworking
	
	["LeatherLeatherArmorOld1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherLeatherArmorOld2"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherLeatherArmorOld3"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherLeatherArmorOld4"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherLeatherArmorOld5"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["LeatherLeatherArmorOld6"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherLeatherArmorBC1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherLeatherArmorBC2"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherLeatherArmorWrath1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherLeatherArmorWrath2"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["LeatherLeatherArmorWrath3"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherMailArmorOld1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherMailArmorOld2"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["LeatherMailArmorBC1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherMailArmorBC2"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherMailArmorWrath1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["LeatherMailArmorWrath2"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["LeatherMailArmorWrath3"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["Dragonscale1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["Elemental1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["Tribal1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	
	-- Tailoring
	
	["TailoringArmorOld1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["TailoringArmorOld2"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["TailoringArmorOld3"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["TailoringArmorOld4"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["TailoringArmorOld5"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["TailoringArmorOld6"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["TailoringArmorOld7"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["TailoringArmorBC1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["TailoringArmorBC2"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["TailoringArmorBC3"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["TailoringArmorWotLK1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["TailoringArmorWotLK2"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["TailoringArmorWotLK3"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["Mooncloth1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["Shadoweave1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["Spellfire1"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	
	--Crafting High Risk

	["AlchemyHighRisk"] = { { "", 1, "CraftingPatternUncommon", "Normal" }, { "", 2, "CraftingPatternsRare", "Rare" }, { "", 3, "CraftingPatternsEpic", "Epic" }, { "", 4, "ItemUncommon", "=s=" }, { "", 5, "ItemRare", "=s=Rare" }, { "", 6, "ItemEpic", "=s=Epic" } },
	["SmithingHighRisk"] = { { "", 1, "CraftingPatternUncommon", "Normal" }, { "", 2, "CraftingPatternsRare", "Rare" }, { "", 3, "CraftingPatternsEpic", "Epic" }, { "", 4, "ItemUncommon", "=s=" }, { "", 5, "ItemRare", "=s=Rare" }, { "", 6, "ItemEpic", "=s=Epic" } },
	["EnchantingHighRisk"] = { { "", 1, "CraftingPatternUncommon", "Normal" }, { "", 2, "CraftingPatternsRare", "Rare" }, { "", 3, "CraftingPatternsEpic", "Epic" } },
	["EngineerHighRisk"] = { { "", 1, "CraftingPatternUncommon", "Normal" }, { "", 2, "CraftingPatternsRare", "Rare" }, { "", 3, "CraftingPatternsEpic", "Epic" }, { "", 4, "ItemUncommon", "=s=" }, { "", 5, "ItemRare", "=s=Rare" },{ "", 6, "ItemEpic", "=s=Epic" } },
	["LeatherHighRisk"] = { { "", 1, "CraftingPatternUncommon", "Normal" }, { "", 2, "CraftingPatternsRare", "Rare" }, { "", 3, "CraftingPatternsEpic", "Epic" }, { "", 4, "ItemUncommon", "=s=" }, { "", 5, "ItemRare", "=s=Rare" },{ "", 6, "ItemEpic", "=s=Epic" } },
	["TailorHighRisk"] = { { "", 1, "CraftingPatternUncommon", "Normal" }, { "", 2, "CraftingPatternsRare", "Rare" }, { "", 3, "CraftingPatternsEpic", "Epic" }, { "", 4, "ItemUncommon", "=s=" }, { "", 5, "ItemRare", "=s=Rare" },{ "", 6, "ItemEpic", "=s=Epic" } },
	["CookingHighRisk"] = { { "", 1, "CraftingPatternUncommon", "Normal" }, { "", 2, "CraftingPatternsRare", "Rare" }, { "", 3, "CraftingPatternsEpic", "Epic" }, { "", 4, "ItemUncommon", "=s=" }, { "", 5, "ItemRare", "=s=Rare" },{ "", 6, "ItemEpic", "=s=Epic" } },
	["CookingHighRiskTwo"] = { { "", 1, "CraftingPatternUncommon", "Normal" }, { "", 2, "CraftingPatternsRare", "Rare" }, { "", 3, "CraftingPatternsEpic", "Epic" }, { "", 4, "ItemUncommon", "=s=" }, { "", 5, "ItemRare", "=s=Rare" },{ "", 6, "ItemEpic", "=s=Epic" } },
	
	
	
	-- Crafted Sets - Tailoring
	
	["TailoringBloodvineG"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["TailoringNeatherVest"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["TailoringImbuedNeather"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["TailoringArcanoVest"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["TailoringWhitemendWis"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["TailoringSpellstrikeInfu"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["TailoringBattlecastG"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["TailoringSoulclothEm"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["TailoringPrimalMoon"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["TailoringShadowEmbrace"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["TailoringSpellfireWrath"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["TailoringFrostwovenPower"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["TailoringDuskweaver"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["TailoringFrostsavageBattlegear"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	
	-- Crafted Sets - Leatherworking - Mail
	
	["LeatherworkingMailGreenDragonM"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingMailBlueDragonM"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingMailBlackDragonM"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingMailScaledDraenicA"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingMailFelscaleArmor"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["LeatherworkingMailFelstalkerArmor"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingMailNetherFury"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingMailNetherscaleArmor"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingMailNetherstrikeArmor"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingMailFrostscaleBinding"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["LeatherworkingMailNerubianHive"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingMailStormhideBattlegear"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingMailSwiftarrowBattlefear"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	

	-- Crafted Sets - Leatherworking - Leather
	
	["LeatherworkingLeatherVolcanicArmor"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingLeatherIronfeatherArmor"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingLeatherStormshroudArmor"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingLeatherDevilsaurArmor"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingLeatherBloodTigerH"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["LeatherworkingLeatherPrimalBatskin"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingLeatherWildDraenishA"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingLeatherThickDraenicA"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingLeatherFelSkin"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingLeatherSClefthoof"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["LeatherworkingLeatherPrimalIntent"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingLeatherWindhawkArmor"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingLeatherBoreanEmbrace"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["LeatherworkingLeatherIceborneEmbrace"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingLeatherEvisceratorBattlegear"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["LeatherworkingLeatherOvercasterBattlegear"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	
	-- Crafted Sets - Blacksmithing - Plate

	["BlacksmithingPlateImperialPlate"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["BlacksmithingPlateTheDarksoul"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["BlacksmithingPlateFelIronPlate"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["BlacksmithingPlateAdamantiteB"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["BlacksmithingPlateFlameG"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["BlacksmithingPlateEnchantedAdaman"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["BlacksmithingPlateKhoriumWard"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["BlacksmithingPlateFaithFelsteel"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	["BlacksmithingPlateBurningRage"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["BlacksmithingPlateOrnateSaroniteBattlegear"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["BlacksmithingPlateSavageSaroniteBattlegear"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },
	
	-- Crafted Sets - Blacksmithing - Mail
	
	["BlacksmithingMailBloodsoulEmbrace"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },	
	["BlacksmithingMailFelIronChain"] = { { "", 1, "CraftingPatterns", "" }, { "", 1, "Normal", "=s=Normal" }, { "", 2, "Bloodforged", 1 }, },


};
