local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Broker_FindGroup", "deDE")
if not L then return end

L["Assembling group..."] = "Gruppe zusammenstellen..."
L["Click to open the dungeon finder."] = "Klicken, um den Dungeonfinder zu öffnen."
L["D"] = "DD"
L["DPS"] = "DD"
L["Find Group"] = "Gruppe finden"
L["H"] = "H"
L["Healer"] = "Heiler"
L["Hide Minimap Button"] = "Minimap-Button verstecken"
L["In Party"] = "In Gruppe"
L["My estimated wait time:"] = "Meine geschätzte Wartezeit: "
L["Queued for: "] = "Angemeldet für: "
L["Right click for options."] = "Rechtsklick für Optionen."
L["Short Text"] = "Kurzform"
L["Show Instance Name"] = "Instanznamen anzeigen"
L["Show Wait Time"] = "Wartezeit anzeigen"
L["T"] = "T"
L["Tank"] = "Tank"
L["Teleport In/Out"] = "Rein/Rausporten"
L["Time"] = "Zeit"
L["Waiting for:"] = "Warte auf: "
L["Wait time as:"] = "Wartezeit als: "
