local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Broker_FindGroup", "zhTW")
if not L then return end

L["Assembling group..."] = "組成隊伍..."
L["Click to open the dungeon finder."] = "點擊後開啟地城搜尋器。"
L["D"] = "輸出"
L["DPS"] = "傷害輸出"
L["Find Group"] = "尋找隊伍"
L["H"] = "補"
L["Healer"] = "治療者"
L["Hide Minimap Button"] = "隱藏小地圖按鈕"
L["In Party"] = "在隊伍中"
L["My estimated wait time:"] = "預計我的等待時間:"
L["Queued for: "] = "排隊等待:"
L["Right click for options."] = "右鍵點擊開啟選項。"
L["Short Text"] = "簡短的文字"
L["Show Instance Name"] = "顯示地城名稱"
L["Show Wait Time"] = "顯示等待時間"
L["T"] = "坦"
L["Tank"] = "坦克"
L["Teleport In/Out"] = "傳送進/出"
L["Time"] = "計時"
L["Waiting for:"] = "已等待:"
L["Wait time as:"] = "等待時間為:"
